name: Check Amazon Time Sale
on:
  schedule:
    # JSTで 毎日 04:30 に設定
    - cron: 30 18 * * *
  repository_dispatch:
    types: [check-link]
  workflow_dispatch:

jobs:
  run:
    name: Yarn
    runs-on: ubuntu-latest
    env:
      REPO: https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
      - name: Use Yarn Cache
        uses: actions/cache@v2
        with:
          path: ${YARN_CACHE_FOLDER}
          key: ${{ runner.os }}-yarn-cache-v1
      - name: Install Dependencies
        run: yarn
      - name: Run build
        run: node index.js
      - name: Commit and Push
        run: |
          git config --global user.email "neg@ipon.biz"
          git config --global user.name "negipon"
          git add .
          git commit -m 'modify' && git push ${REPO} HEAD:${{github.event.pull_request.head.ref}} || true
