name: Check Amazon Time Sale
on:
  schedule:
    # JSTで 毎週日曜 00:30 に設定
    # 5番目に0（日曜日）を指定
    - cron: 30 14 * * 0

jobs:
  run:
    name: Yarn
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@main
      - name: Use Yarn Cache
        uses: actions/cache@v2
        with:
          path: ${YARN_CACHE_FOLDER}
          key: ${{ runner.os }}-yarn-cache-v1
      - name: Install Dependencies
        run: yarn
      - name: Run build
        run: node index.js
